using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorPower.Options
{
    [Generator]
    public class OptionsGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new OptionsSyntax());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is OptionsSyntax receiver))
            {
                return;
            }

            var optionsVisitor = new OptionsVisitor();
            foreach (var assemblySymbol in context.Compilation.SourceModule.ReferencedAssemblySymbols
                         .Where(x => x.Identity.PublicKeyToken == ImmutableArray<byte>.Empty))
            {
                assemblySymbol.Accept(optionsVisitor);
            }

            receiver.TypeSymbols.AddRange(optionsVisitor.GetOptionsTypes());

            INamedTypeSymbol attributeSymbol =
                context.Compilation.GetTypeByMetadataName("SourceGeneratorPower.Options.OptionAttribute");

            StringBuilder source = new StringBuilder($@"
namespace Microsoft.Extensions.DependencyInjection
{{
    public static class ScanInjectOptions
    {{
        public static void AutoInjectOptions(this IServiceCollection services, IConfiguration configuration)
        {{
");
            foreach (var symbol in receiver.TypeSymbols)
            {
                source.Append(' ', 12);
                source.AppendLine(ProcessOptions(symbol, attributeSymbol));
            }

            source.Append(' ', 8).AppendLine("}")
                .Append(' ', 4).AppendLine("}")
                .AppendLine("}");
            context.AddSource("Options.AutoGenerated.cs",
                SourceText.From(source.ToString(), Encoding.UTF8));
        }

        private string ProcessOptions(ISymbol typeSymbol, ISymbol attributeSymbol)
        {
            AttributeData attributeData = typeSymbol.GetAttributes()
                .Single(ad => ad.AttributeClass!.Equals(attributeSymbol, SymbolEqualityComparer.Default));
            TypedConstant path = attributeData.ConstructorArguments.First();
            return $@"services.Configure<{typeSymbol.ToDisplayString()}>(configuration.GetSection(""{path.Value}""));";
        }

        class OptionsSyntax : ISyntaxContextReceiver
        {
            public List<ISymbol> TypeSymbols { get; set; } = new List<ISymbol>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0)
                {
                    var typeSymbol = context.SemanticModel.GetDeclaredSymbol(cds);
                    if (typeSymbol!.GetAttributes().Any(x =>
                            x.AttributeClass!.ToDisplayString() ==
                            "SourceGeneratorPower.Options.OptionAttribute"))
                    {
                        TypeSymbols.Add(typeSymbol);
                    }
                }
            }
        }

        class OptionsVisitor : SymbolVisitor
        {
            private readonly HashSet<INamedTypeSymbol> _optionsTypeSymbols;

            public OptionsVisitor()
            {
                _optionsTypeSymbols = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            }

            public ImmutableArray<INamedTypeSymbol> GetOptionsTypes() => _optionsTypeSymbols.ToImmutableArray();

            public override void VisitAssembly(IAssemblySymbol symbol)
            {
                symbol.GlobalNamespace.Accept(this);
            }

            public override void VisitNamespace(INamespaceSymbol symbol)
            {
                foreach (var namespaceOrTypeSymbol in symbol.GetMembers())
                {
                    namespaceOrTypeSymbol.Accept(this);
                }
            }

            public override void VisitNamedType(INamedTypeSymbol symbol)
            {
                if (symbol.DeclaredAccessibility != Accessibility.Public)
                {
                    return;
                }

                if (symbol.GetAttributes().Any(x =>
                        x.AttributeClass!.ToDisplayString() == "SourceGeneratorPower.Options.OptionAttribute"))
                {
                    _optionsTypeSymbols.Add(symbol);
                }

                var nestedTypes = symbol.GetMembers();
                if (nestedTypes.IsDefaultOrEmpty)
                {
                    return;
                }

                foreach (var nestedType in nestedTypes)
                {
                    nestedType.Accept(this);
                }
            }
        }
    }
}